version: "3"
services:
  backend:
    image: ysaddem/examScrum-1.0.0:tag8
    ports:
      - "8089:8089"
    restart: unless-stopped
    container_name: spring
    depends_on:
      - sql_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sql_db:3306/exam_scrum?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  sql_db:
    image: ysaddem/mysql:1
    container_name: sql_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=exam_scrum
    volumes:
      - "db_volume:/var/lib/mysql"

volumes:
  db_volume: {}